### ISSUE TITLE
[Feature Request]: Auto elevate

### ISSUE THREAD

**Issue by Dragon1573** [RimuruChan/vscode-fix-checksums#2]
## Summary

I'm currently running an "system setup" version of VSCode.

This extensions modifies core files of VSCode, so when I launch VSCode with Desktop Shortcuts as normal, VSCode won't automatically elevated and the extension have no permissions to modify those files.

![image](https://github.com/user-attachments/assets/5c5b9ea5-ce11-4931-8374-598b52814723)

Could you please add a feature for asking UAC Administrator privileges approval? When such case detected, the extension will popup an UAC dialog, requesting user's authentication to elevate and modify files.

## Information of VSCode

| Parameter       | Value                                      |
|:----------------|:-------------------------------------------|
| Version         | 1.92.2 (system setup)                      |
| Commits         | `fee1edb8d6d72a0ddff41e5f71a671c23ed924b9` |
| Date            | 2024-08-14T17:29:30.058Z                   |
| Electron        | 30.1.2                                     |
| ElectronBuildId | 9870757                                    |
| Chromium        | 124.0.6367.243                             |
| Node.js         | 20.14.0                                    |
| V8              | 12.4.254.20-electron.0                     |
| OS              | Windows_NT x64 10.0.22631                  |

## Information of Extension

| Parameter | Description |
|:----------|:------------|
| Version   | v1.2.0      |

**Comment by RimuruChan** [comment]
I’m not quite sure how to implement this. If you know how, feel free to submit a PR. Maybe you can try running VSCode in admin mode temporarily or switch to the user directory version for installation.

**Comment by Dragon1573** [comment]
According to source code, it seems privileges issues may encounter while renaming and writing `product.json`.

https://github.com/RimuruChan/vscode-fix-checksums/blob/29448b46471729663cc885c0fafcf180e919b79b/extension.js#L40-L49

When we directly modify the JSON file in editor panel and save it, a dialog will pop up for asking elevation.

![image](https://github.com/user-attachments/assets/a81ffe86-5cbd-4f55-a247-74ed9720507b)

Can we use this mechanism for asking elevation? Can a VSCode extension ask for an elevation like this? Is it complicated to implement? 🙏🏼

**Comment by zent1n0** [comment]
> Can we use this mechanism for asking elevation? Can a VSCode extension ask for an elevation like this? Is it complicated to implement? 🙏🏼

The message box is provided by VSCode editor, while extension use Node.js function to write file(s).

It's nice of you if you can provide some examples of extension which implemented your thoughts.

**Comment by RimuruChan** [comment]
There exists an internal API in VSCode, but I have no idea how to use it in an extension.

**Comment by Dragon1573** [comment]
> It's nice of you if you can provide some examples of extension which implemented your thoughts.

Following contents are copied from another fork. But that seems not released to Marketplace yet before it's archived.

### Related commits

- Introduce dependencies for elevation: https://github.com/spikespaz-contrib/vscode-fix-checksums/commit/0cb8f996d4a4921c369ff7e2ae5cbbacf5368f3f
- Create a new function and write file with admin priviledges: https://github.com/spikespaz-contrib/vscode-fix-checksums/commit/bbd91db0e51befae72b692dc7961be1983088ce7

### Related pull requests

- lehni/vscode-fix-checksums#1

**Comment by RimuruChan** [comment]
I'm wondering if this would work on macos, could anyone test this? (v1.3.0)

If this works then I think I'll update the readme.

@Zylsjsp Could you test it?

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Feature request of providing elevation API for extensions is already created. We have 60 days to vote up for the feature. Could someone else vote for it please? So we can just invoke provided API from VSCode itself instead of introducing `sudo-prompt` and implement this elevation on our own. 🙏🏼
>
> - See https://github.com/microsoft/vscode/issues/231084#issuecomment-2412906400

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Feature request of providing elevation API for extensions is already open. Really need help for upvoting it to be included in the backlog. 🙏🏼
>
> - See https://github.com/microsoft/vscode/issues/231084#issuecomment-2412906400

**Comment by zent1n0** [comment]
This issue only occurs when using a Windows VSCode systemwide installation. Not with any user installation.
On MacOS VSCode installs as a user application, so there's no issue with permission.

Besides, on GNU/Linux based systems, permission could be obtained through an VSCode message box.

**Comment by Dragon1573** [comment]
> This issue only occurs when using a Windows VSCode systemwide installation. Not with any user installation.

I'm facing this problem with **System Setup** version of VSCode on Windows 11. So I create this feature request. ❤️

**Comment by zent1n0** [comment]
> I'm facing this problem with **System Setup** version of VSCode on Windows 11. So I create this feature request. ❤️

Yep. I'm mainly responding to @RimuruChan. Please be reminded any user setup works well before.
